const translations = {
    "en": {
        //akkim
        "akkim-h1" : "Akkim Epoxy Plant & Control Building",
        "akkim-p" : "The electrical installation work of the “Mithra Technical Yarn Factory,” with a construction area of 35,000 m² and an installed capacity of 10 MW, owned by Aksa Akrilik Kimya Sanayi A.Ş., a subsidiary of Akkök Holding located in the Çiftlikköy district of Yalova, is planned to be completed and handed over by the end of 2024.",
        "akkim-li-1" : "Public Address & Voice Evacuation Sys.",
        "akkim-li-2" : "Low Voltage Distribution System",
        "akkim-li-3" : "Main Distribution Electrical Panel",
        "akkim-li-4" : "Lighting System",
        "akkim-li-5" : "Building automation System",
        "akkim-li-6" : "CCTV System",
        "akkim-li-7" : "Perimeter Lighting & Elect. Infrastructure",
        "akkim-li-8" : "Distribution, MCC & Comp. Panels",
        "akkim-li-9" : "Data/Network System",
        "akkim-li-10" : "Gas & Foam Fire Suppression System",
        "akkim-li-11" : "Construction Site Mobilization",
        "akkim-li-12" : "Tv System",
        "akkim-li-13" : "UPS System",
        "akkim-li-14" : "Fire Detection & Alarm System",
        "akkim-li-15" : "Lighting Protection & Grounding",
        "akkim-card-p1" : "Electrical Contracting",
        "akkim-card-p2" : "Akkim Epoxy Plant & Control Building",
        "akkim-card-p3" : "2024",
        "akkim-card-p4" : "Yalova, Çiftlikköy",

        //sisecam
        "sisecam-h1" : "Sisecam Flat Glass Tarsus Factory Logistics Center",
        "sisecam-p" : "Located in the Tarsus district of Mersin, the Flat Glass Tarsus Factory Logistics Center and Sand Preparation Facility, owned by Türkiye Şişe ve Cam Fabrikaları A.Ş., has a construction area of 72,482 m². The facility, with an installed capacity of 20 MW, will be delivered upon completion of its electrical installation works.",
        "sisecam-li-1" : "Public Address & Voice Evacuation Sys.",
        "sisecam-li-2" : "Low Voltage Distribution System",
        "sisecam-li-3" : "Main Distribution Electrical Panel",
        "sisecam-li-4" : "Lighting System",
        "sisecam-li-5" : "Building automation System",
        "sisecam-li-6" : "Busbar Distribution System",
        "sisecam-li-7" : "CCTV System",
        "sisecam-li-8" : "Perimeter Lighting & Elect. Infrastructure",
        "sisecam-li-9" : "Distribution, MCC & Comp. Panels",
        "sisecam-li-10" : "Data/Network System",
        "sisecam-li-11" : "Gas & Foam Fire Suppression System",
        "sisecam-li-12" : "Construction Site Mobilization",
        "sisecam-li-13" : "Generator System",
        "sisecam-li-14" : "Card Access Control System",
        "sisecam-li-15" : "Power Busbar System",
        "sisecam-card-p1" : "Electrical Contracting",
        "sisecam-card-p2" : "Sisecam Flat Glass Tarsus Factory Logistics Center",
        "sisecam-card-p3" : "Ongoing",
        "sisecam-card-p4" : "Mersin, Tarsus",

        //sertifikalar
        "sertifika" : "Certificates",

        //danışmanlık
        "danişmanlik-h1" : "PROJECT & CONSULTANCY",
        "danişmanlik-p" : "As a company specializing in electrical project design and engineering solutions, we provide high-quality services to make your electrical infrastructure safe, efficient, and sustainable. We offer a comprehensive range of services in electrical project design, implementation, and consulting, working alongside you at every stage of your projects.",
        "danişmanlik-proje-h1" : "Project",
        "danişmanlik-proje-p" : "We prepare technical drawings of electrical projects, including low and medium voltage, lighting, power distribution, fire detection, and security systems, in compliance with national and international standards.",
        "danişmanlik-danişmanlik-h1" : "Consultancy",
        "danişmanlik-danişmanlik-p" : " We provide the professional consulting services you need for your projects, offering technical support at every stage. We deliver reliable and efficient solutions in the planning, design, implementation, and management processes of your projects, in compliance with national and international standards.",
        //home
        "navHome": "Home",
        "navProjects": "Projects",
        "navAbout": "About",
        "navServices": "Services",
        "navContact": "Contact",
        "proje": "Project",

        //elec
        "elec-header-h": "Electrical Contracting",
        "elec-header-p": "We prepare technical drawings of electrical projects, including low and medium voltage, lighting, power distribution, fire detection, and security systems, in compliance with national and international standards.",
        //elec-1
        "elec-1-h": "1. Industrial Electrical Installation",
        "elec-1-p": "We provide safe, efficient and sustainable electrical solutions in industrial plants. Our services include energy distribution systems, motor control centers, automation systems and special process electrical installations.",
        "elec-1-li-1-h": "Energy Distribution Systems: ",
        "elec-1-li-1-p": "Safe and efficient energy distribution in factories and production facilities.",
        "elec-1-li-2-h": "Motor Control Centers: ",
        "elec-1-li-2-p": "Solutions for control and automation of industrial motors.",
        "elec-1-li-3-h": "Automation Systems: ",
        "elec-1-li-3-p": "Automation of production processes and increasing productivity.",
        "elec-1-li-4-h": "Process Electrical Installations: ",
        "elec-1-li-4-p": "Electrical installations suitable for special production processes.",
        //elec-2
        "elec-2-h": "2. Commercial Buildings and Offices",
        "elec-2-p": "We offer complete electrical solutions for commercial buildings, offices and shopping centers. With services covering lighting systems, energy management, security systems and more, we meet the needs of commercial spaces.",
        "elec-2-li-1-h": "Lighting Systems: ",
        "elec-2-li-1-p": "Energy efficient and aesthetic lighting solutions.",
        "elec-2-li-2-h": "Energy Management: ",
        "elec-2-li-2-p": "Optimization of energy consumption in commercial buildings.",
        "elec-2-li-3-h": "Security Systems: ",
        "elec-2-li-3-p": "Fire alarm systems, CCTV and access control systems.",
        "elec-2-li-4-h": "Building Automation: ",
        "elec-2-li-4-p": "Modern and efficient office environments with smart building systems.",
        //elec-3
        "elec-3-h": "3. Housing Projects",
        "elec-3-p": "We offer comprehensive electrical installation services for residential projects. We provide safe and modern electrical solutions for apartment buildings, villa complexes and individual residences.",
        "elec-3-li-1-h": "Basic Electrical Installation: ",
        "elec-3-li-1-p": "Full range of electrical installations for new residential projects.",
        "elec-3-li-2-h": "Lighting and Socket Installation: ",
        "elec-3-li-2-p": "Indoor lighting and socket placement..",
        "elec-3-li-3-h": "Smart Home Systems: ",
        "elec-3-li-3-p": "Modernization of living spaces with smart home technologies.",
        "elec-3-li-4-h": "Security Systems: ",
        "elec-3-li-4-p": "Alarm and CCTV systems for home security.",
        //elec-4
        "elec-4-h": "4. Public and Education Buildings",
        "elec-4-p": "We offer electrical contracting services for public buildings, schools, hospitals and other educational structures. Safety, efficiency and user-friendly solutions are our priority in these buildings.",
        "elec-4-li-1-h": "Lighting Systems: ",
        "elec-4-li-1-p": "Appropriate lighting solutions for public and educational buildings..",
        "elec-4-li-2-h": "Energy Distribution and Management: ",
        "elec-4-li-2-p": "Energy distribution and management in public buildings.",
        "elec-4-li-3-h": "Emergency Systems: ",
        "elec-4-li-3-p": "Fire alarm, emergency exit lighting and backup power systems.",
        "elec-4-li-4-h": "IT and Communication Infrastructure: ",
        "elec-4-li-4-p": "IT infrastructure solutions for education and public buildings.",
        //elec-5
        "elec-5-h": "Weak Current Systems",
        "elec-5-li-1": "Public Address and Emergency Announcement System",
        "elec-5-li-2": "Fire Detection and Warning System",
        "elec-5-li-3": "Card Access System",
        "elec-5-li-4": "TV/IPTV/SMATV System",
        "elec-5-li-5": "Data System",
        "elec-5-li-6": "Parking Lot Guidance System",
        "elec-5-li-7": "Central Clock System",
        "elec-5-li-8": "Radio System",
        "elec-5-li-9": "SCADA",
        //elec-6
        "elec-6-h": "Low Voltage Systems",
        "elec-6-li-1": "Busbar Distribution System",
        "elec-6-li-2": "Distribution, MCC and Compensation Panels",
        "elec-6-li-3": "Cable Transportation System",
        "elec-6-li-4": "Lighting Armature Installations",
        "elec-6-li-5": "Lighting - Air Conditioning Automation",
        "elec-6-li-6": "UPS Installations and Building Automation",
        "elec-6-li-7": "Generator System",
        "elec-6-li-8": "Lightning Protection and Grounding",
        "elec-6-li-9": "SCADA and Energy Monitoring Automation",
        //elec-7
        "elec-7-h": "Medium Voltage Systems",
        "elec-7-li-1": "M.V. Energy Supply and Distribution",
        "elec-7-li-2": "Transformer and MV Supply and Installation Works",
        "elec-7-li-3": "Test and Commissioning Works",
        "elec-7-li-4": "Provision of Energy Consent Certificate and Electricity Administration Acceptance Works",
        //renew
        "renew-header-h": "Renewable Energy",
        "renew-header-p": "We provide sustainable energy solutions by installing environmentally friendly renewable energy systems in your projects. With our team of expert engineers and technicians, we ensure high efficiency and reliability throughout the design, installation, and  commissioning processes.",
        //renew-1
        "renew-1-h": "1. Solar Energy Systems",
        "renew-1-p": "Solar energy is a clean and inexhaustible source of energy. As Magma Group, we meet the energy needs of our customers by installing solar energy systems in various scales.",
        "renew-1-li-1-h": "Rooftop Solar Energy Systems: ",
        "renew-1-li-1-p": "Photovoltaic panels installed on roofs for residences, commercial buildings and industrial facilities.",
        "renew-1-li-2-h": "Land Type Solar Energy Systems: ",
        "renew-1-li-2-p": "Solar power plants installed on large areas of land for large-scale energy production.",
        "renew-1-li-3-h": "Energy Storage Systems: ",
        "renew-1-li-3-p": "Energy storage and management with batteries integrated into solar energy systems.",
        "renew-1-li-4-h": "Hybrid Systems: ",
        "renew-1-li-4-p": "Hybrid solutions that provide uninterrupted energy using both solar and grid energy.",
        //renew-2
        "renew-2-h": "2.Energy Efficiency Projects",
        "renew-2-p": "Energy efficiency is critical for both reducing costs and reducing environmental impacts. As Magma Group, we offer more sustainable solutions to our customers through energy efficiency projects.",
        "renew-2-li-1-h": "Energy Audit: ",
        "renew-2-li-1-p": "Analyzing energy consumption in buildings and facilities and identifying efficiency opportunities.",
        "renew-2-li-2-h": "Energy Management Systems: ",
        "renew-2-li-2-p": "Solutions for monitoring, managing and optimizing energy consumption.",
        "renew-2-li-3-h": "Efficient Lighting Systems: ",
        "renew-2-li-3-p": "Energy-saving LED lighting and smart lighting systems.",
        "renew-2-li-4-h": "Insulation and Heat Recovery: ",
        "renew-2-li-4-p": "Insulation solutions and heat recovery systems to prevent energy loss in buildings.",
        //renew-3
        "renew-3-h": "Solar Energy System",
        "renew-3-li-1": "Rooftop Solar Power System",
        "renew-3-li-2": "Land Solar Power System",
        "renew-3-li-3": "Energy Storage System",
        "renew-3-li-4": "Hybrid Systems",
        //renew-4
        "renew-4-h": "Energy Efficiency Projects",
        "renew-4-li-1": "Energy Audit",
        "renew-4-li-2": "Energy Management Systems",
        "renew-4-li-3": "Efficient Lighting Systems",
        "renew-4-li-4": "Insulation and Heat Recovery",

        //projects
        "projects-h1": "OUR PROJECTS",
        "projects-p1": "CBRT Ümraniye Additional Campus",
        "projects-p2": "Dowaksa-Linde Road Lighting",
        "projects-p3": "Dowaksa Carbon Fiber Factory Capacity Expansion Project",
        "projects-p4": "ÇOSB Environmental Lighting and Camera Infrastructure",
        "projects-p5": "Aksafil Acrylic Yarn Factory and Product Warehouse",
        "projects-p6": "Akcennet Recreation Area Lighting",
        "projects-p7": "Arçelik Washing Machine Factory",
        "projects-p8": "Aksa Truck Parking Area",
        "projects-p9": "Akbatı Shopping Mall Solar Power Plant",
        "projects-p10": "Akasya Shopping Mall Solar Power Plant",
        "projects-p11": "Mithra Technical Yarn Factory",
        "projects-p12": "Sisecam Flat Glass Tarsus Factory Logistics Center",
        "projects-p13": "Akkim Epoxy Plant & Control Building",
        "projects-t": "Contracting",
        "projects-y": "Renewable Energy",
        "projects-photos-h": "Photos",
            
        // TCMB Project
        "projects-tcmb-header": "CBRT Ümraniye Additional Campus",
        "projects-tcmb-p": "The project, which started in October 2019 in Ümraniye, Istanbul, was completed in March 2020. The structure, which has a closed area of approximately 21,000 m², consists of a total of 15 floors, including 13 regular floors and 2 parking levels.",
        "projects-tcmb-h-1": "Project Details",
        "projects-tcmb-h-2": "Completed Works:",
        "projects-tcmb-li-1": "Lighting System",
        "projects-tcmb-li-2": "Low Voltage Distribution System",
        "projects-tcmb-li-3": "Fire Detection and Alarm System",
        "projects-tcmb-li-4": "Emergency Announcement and Sound System",
        "projects-tcmb-li-5": "Card Access System",
        "projects-tcmb-li-6": "Data/Network System",
        "projects-tcmb-li-7": "Busbar Distribution System",
        "projects-tcmb-li-8": "Distribution, MCC, and Compensation Panels",
        "projects-tcmb-li-9": "Building Automation System",
        "projects-tcmb-li-10": "UPS System",
        "projects-tcmb-li-11": "Generator System",
        "projects-tcmb-li-12": "Lightning Protection and Grounding",
        "projects-tcmb-li-13": "Medium Voltage System",
        "projects-tcmb-card-h1": "Project: ",
        "projects-tcmb-card-h2": "Project Name: ",
        "projects-tcmb-card-h3": "Year: ",
        "projects-tcmb-card-h4": "Address: ",
        "projects-tcmb-card-p1": "Electrical Contracting",
        "projects-tcmb-card-p2": "Central Bank of the Republic of Turkey – Ümraniye Additional Campus",
        "projects-tcmb-card-p3": "2019",
        "projects-tcmb-card-p4": "Istanbul, Ümraniye",
        
        // Dowaksa-Linde Road Lighting
        "projects-linde-header": "Dowaksa-Linde Road Lighting",
        "projects-linde-p": "The lighting of the Linde road in the Dowaksa facility, located in Çiftlikköy, Yalova, under Akkök Holding, was completed and delivered in 2021.",
        "projects-linde-li-1": "Polygon Type Lighting Pole Application",
        "projects-linde-card-p1": "Electrical Contracting",
        "projects-linde-card-p2": "Dowaksa-Linde Road Lighting",
        "projects-linde-card-p3": "2021",
        "projects-linde-card-p4": "Yalova, Çiftlikköy",
        
        // Dowaksa Carbon Fiber Factory Capacity Expansion Project
        "projects-dowaksa-header": "Dowaksa Carbon Fiber Factory Capacity Expansion Project",
        "projects-dowaksa-p": "The electrical installation of the Carbon Fiber Composite Material Production Facility of Dowaksa Advanced Composite Materials Ltd., located in Çiftlikköy, Yalova, under Akkök Holding, was completed and delivered in 2024. The facility, established on an area of 117,000 m², consists of 18 independent buildings.",
        "projects-dowaksa-li-1": "Low Voltage Distribution System",
        "projects-dowaksa-li-2": "Distribution Panels",
        "projects-dowaksa-li-3": "Fire Detection and Alarm System",
        "projects-dowaksa-li-4": "Emergency Announcement and Sound System",
        "projects-dowaksa-li-5": "Lighting System",
        "projects-dowaksa-li-6": "Lightning Protection and Grounding",
        "projects-dowaksa-li-7": "CCTV System",
        "projects-dowaksa-li-8": "Gas and Foam Fire Suppression Detection",
        "projects-dowaksa-li-9": "Environmental Lighting and Infrastructure",
        "projects-dowaksa-li-10": "Data / Network System",
        "projects-dowaksa-card-p1": "Electrical Contracting",
        "projects-dowaksa-card-p2": "Dowaksa – Carbon Fiber Factory Capacity Expansion Project",
        "projects-dowaksa-card-p3": "2024",
        "projects-dowaksa-card-p4": "Yalova, Çiftlikköy",
        
        // ÇOSB Environmental Lighting and Camera Infrastructure
        "projects-cosb-header": "ÇOSB Environmental Lighting and Camera Infrastructure",
        "projects-cosb-p": "The street lighting and security camera infrastructure of the streets within Çerkezköy Organized Industrial Zone, located in Kapaklı, Tekirdağ, and the Advanced Biological Treatment Plant were completed and delivered in 2021.",
        "projects-cosb-li-1": "Street Lighting Poles",
        "projects-cosb-li-2": "Camera Poles",
        "projects-cosb-li-3": "UPS System",
        "projects-cosb-card-p1": "Electrical Contracting",
        "projects-cosb-card-p2": "Çerkezköy Organized Industrial Zone – Environmental Lighting and Camera Infrastructure",
        "projects-cosb-card-p3": "2021",
        "projects-cosb-card-p4": "Tekirdağ, Kapaklı",
        //projects-aksafil
        "projects-aksafil-header": "Aksafil Acrylic Yarn Factory and Product Warehouse",
        "projects-aksafil-p": "The electrical installation work of the 'Airjet Acrylic Yarn Factory and Raw Material Warehouse,' owned by Aksa Akrilik Kimya Sanayi A.Ş., a subsidiary of Akkök Holding, located in the Çiftlikköy district of Yalova, with a construction area of 28,716 m² and an installed power of 8 MW, was completed and delivered in 2023.",
        "projects-aksafil-li-1": "Lighting System",
        "projects-aksafil-li-2": "Low Voltage Distribution System",
        "projects-aksafil-li-3": "Fire Detection and Alarm System",
        "projects-aksafil-li-4": "Emergency Announcement and Public Address System",
        "projects-aksafil-li-5": "Data/Network System",
        "projects-aksafil-li-6": "Busbar Distribution System",
        "projects-aksafil-li-7": "Distribution Panels",
        "projects-aksafil-li-8": "Lightning Protection and Grounding",
        "projects-aksafil-li-9": "Medium Voltage System",
        "projects-aksafil-li-10": "Site Mobilization",
        "projects-aksafil-card-p1": "Electrical Contracting",
        "projects-aksafil-card-p2": "Aksa – Airjet Yarn Factory and Raw Material Warehouse",
        "projects-aksafil-card-p3": "2023",
        "projects-aksafil-card-p4": "Yalova, Çiftlikköy",
        //projects-akcennet
        "projects-akcennet-header": "Akcennet Recreation Area Lighting",
        "projects-akcennet-p": "The environmental lighting work of the recreation area belonging to Aksa Acrylic Fiber Factory, a subsidiary of Akkök Holding, located in the Çiftlikköy district of Yalova, was completed and delivered in 2020.",
        "projects-akcennet-li-1": "Decorative Lighting Poles",
        "projects-akcennet-li-2": "Bollard Decorative Lighting",
        "projects-akcennet-li-3": "Combination Socket System",
        "projects-akcennet-li-4": "Polygon Lighting Poles",
        "projects-akcennet-card-p1": "Electrical Contracting",
        "projects-akcennet-card-p2": "Aksa – Akcennet Recreation Area Lighting",
        "projects-akcennet-card-p3": "2020",
        "projects-akcennet-card-p4": "Yalova, Çiftlikköy",
        //projects-arcelik
        "projects-arcelik-header": "Arçelik Washing Machine Factory",
        "projects-arcelik-p": "The medium voltage electrical infrastructure work of the Arçelik Washing Machine Factory, located in the Manisa Organized Industrial Zone in the Yunus Emre district of Manisa, with a power of 20 MW (8×2.5MW), was completed and delivered in 2024.",
        "projects-arcelik-li-1": "Transformer Center",
        "projects-arcelik-li-2": "Power Busbar System",
        "projects-arcelik-li-3": "Fire Detection and Alarm System",
        "projects-arcelik-li-4": "Emergency Announcement and Public Address System",
        "projects-arcelik-li-5": "Main Distribution Panel",
        "projects-arcelik-card-p1": "Electrical Contracting",
        "projects-arcelik-card-p2": "Arçelik – Washing Machine Factory Electrical Medium Voltage Infrastructure",
        "projects-arcelik-card-p3": "2024",
        "projects-arcelik-card-p4": "Manisa, Yunus Emre",
        //projects-aksa
        "projects-aksa-header": "Aksa Truck Parking Lot",
        "projects-aksa-p": "The electrical installation of the truck parking lot, belonging to Akkök Holding and located in the Çiftlikköy district of Yalova, was completed and delivered in 2022.",
        "projects-aksa-li-1": "Polygon Type Pole Installation",
        "projects-aksa-li-2": "Lighting Installation",
        "projects-aksa-li-3": "Camera Infrastructure",
        "projects-aksa-li-4": "Combination Socket Installation",
        "projects-aksa-card-p1": "Electrical Contracting",
        "projects-aksa-card-p2": "Aksa – Truck Parking Lot Lighting",
        "projects-aksa-card-p3": "2022",
        "projects-aksa-card-p4": "Yalova, Çiftlikköy",
        //projects-akbati
        "projects-akbati-header": "Akbatı Shopping Mall Solar Power Plant",
        "projects-akbati-p": "A solar power plant was installed on the roof of Akbatı Shopping Mall, located in the Esenyurt district of Istanbul, and was delivered in 2023.",
        "projects-akbati-card-h1": "Capacity: ",
        "projects-akbati-card-p1-1": "Renewable Energy",
        "projects-akbati-card-p1-2": "Solar Power Plant",
        "projects-akbati-card-p2": "Akbatı Shopping Mall Rooftop Solar Power Plant",
        "projects-akbati-card-p3": "915kWp/750kWe",
        "projects-akbati-card-p4": "2023",
        "projects-akbati-card-p5": "Istanbul, Esenyurt",
        //projects-akasya
        "projects-akasya-header": "Akasya Shopping Mall Solar Power Plant Project",
        "projects-akasya-p": "A solar power plant was installed on the roof of Akasya Shopping Mall, located in the Kadıköy district of Istanbul, and was delivered in 2023.",
        "projects-akasya-card-h1": "Capacity: ",
        "projects-akasya-card-p1-1": "Renewable Energy",
        "projects-akasya-card-p1-2": "Solar Power Plant",
        "projects-akasya-card-p2": "Akasya Shopping Mall Rooftop Solar Power Plant",
        "projects-akasya-card-p3": "773kWp/750kWe",
        "projects-akasya-card-p4": "2023",
        "projects-akasya-card-p5": "Istanbul, Kadıköy",


        "services": "SERVICES",




        "why": "Why",
        "whyuse1": "Expertise and Experience",
        "whyuse1.1": "With our experienced team, we produce solutions that are tailored to the unique needs of each project. Our extensive knowledge and expertise in projects enable us to deliver the best results to our customers.",
                "whyuse2": "Technological Innovations",
        "whyuse2.1":"Using the latest technologies in the sector, we design systems with high energy efficiency and long life. With our innovative approach, we increase the performance and sustainability of our projects.",
                "whyuse3": "Environmentally Friendly Solutions",
        "whyuse3.1":"We are committed to providing environmentally friendly and sustainable energy solutions. With our renewable energy projects, we aim to reduce our carbon footprint and minimize environmental impacts.",
        "whyuse4": "Customer Satisfaction",
        "whyuse4.1": "Customer satisfaction is at the heart of our business. We work closely with our customers at every stage of the project, aiming to exceed their expectations.",
        "whyuse5": "Quality and Safety",
        "whyuse5.1": "We apply the highest quality and safety standards in all our projects. We adhere to our quality control procedures at every stage, from the materials used to the workmanship details.",
        "whyuse6": "Work, Occupational Health and Safety",
        "whyuse6.1": "We adopt the highest standards in occupational health and safety. Ensuring the safety of our employees and stakeholders in all our projects is our top priority.",
        "referances":"Our References","about": "ABOUT US",
        "about1": "As Magma Group, we have ethical rules that we are responsible for complying with and guiding in terms of compliance while growing our business. We continue on our way with the principle of working based on people, society and nature. We adopt being transparent, fair and accountable in our relationships. Our core values ​​are honesty, integrity and respect in the decisions we make.These principles were created to guide our managers, employees and business partners.",
        "etik":"Ethical Principles",
        "etik1":"1. Respect for Human Rights and Prevention of Discrimination",
        "etik2":"2. Compliance with Laws - GDPR - Information Confidentiality",
        "etik3":"3. Occupational Health and Safety",
        "etik4":"4. Environmental Protection",
        "etik5":"5. Stakeholder Relations",


        "etik1.1":"Our only criterion for recruitment is suitability for the job. Gender, language, religion, race, color, age are not considered.",
        "etik1.2":"We aim to increase loyalty to the company by rewarding success through fair and competitive wage policies, effective and objective performance evaluation system and practices.",
        "etik1.3":"Opportunities are provided for the training and development of our employees.",
        "etik1.4":"A transparent working environment that encourages mutual respect is created.",
        "etik1.5":"No form of discrimination, violence and harassment is tolerated.",
        "etik1.6":"Our employees are provided with clean, healthy and safe working conditions.",
        "etik1.7":"We do not tolerate child labor and forced labor.",

        "etik2.1":"Wherever we do business, we act in accordance with the law and consult the competent authorities when necessary.",
        "etik2.2":"Respecting intellectual and industrial property rights is our basic principle in this area.",
        "etik2.3":"We act in accordance with legal regulations in the processing of personal data and take the necessary measures. In this context, we act in accordance with the local and international legislation we are subject to and the principles determined in the processing of personal data under all circumstances.",
        "etik2.4":"We ensure that all our commercial activities and records and agreements with third parties are in compliance with the legislation, our Code of Ethics and policies, and are clear and understandable.",
        "etik2.5":"Our employees may not directly, indirectly or through third parties, accept or receive bribes, any benefits or facilitating payments from any person or organization.",
        "etik2.6":"Our employees are responsible for acting in compliance with all applicable laws and regulations on anti-money laundering and anti-corruption.",
        "etik2.7":"The information belonging to our employees is only used for the purposes of Magma Group by authorized persons in case of need.",
        "etik2.8":"Our Group employees are expected to protect confidential information obtained within the scope of their work and use it only for company purposes. Confidential information can be defined as financial, strategic, technical, commercial, personnel personal rights, matters covered by confidentiality agreements with third parties and similar information that belongs to the company and is not known by third parties, which, if known, may cause damage to the company and/or its stakeholders or may benefit others.",

        "etik3.1":"It is aimed to ensure full occupational health and safety. Employees act in accordance with the rules and instructions set for this purpose and take the necessary precautions.",
        "etik3.2":"Employees may not keep any item or substance in the workplace that poses a danger to the workplace and/or workers or that is illegal.",

        "etik4.1":"Magma Group uses the most appropriate methods possible to minimize the negative effects of wastes and products on the environment and to reduce the use of natural resources.",
        "etik4.2":"In order to protect the environment and keep it clean, Magma Group conserves limited resources and saves energy.",

        "etik5.1":"Magma Group always acts in a professional and fair manner based on trust and honesty in its relations with its business partners, customers, suppliers and other stakeholders. It shows due diligence to fulfill mutual obligations on time.",
        "etik5.2":"In our selection of suppliers, dealers, authorized dealers and authorized services, we objectively evaluate the fulfillment of legal obligations that attach importance to human rights, take into account the principles of anti-bribery and anti-corruption.",
        "buton":"About",


        "buton1":"Company Name:",
        "buton2":"Tax Office:",
        "buton3":"Tax Number:",
        "buton4":"Trade Registry Number",
        "buton5":"Mersis Number:",
        "buton6":"CENTER OFFICE",
        "buton7":"TECNICAL OFFICE",
        "buton8":"PHONE",
        "buton9":"E-MAIL",


//about
"about-p-1":"Founded in 2019, Magma Group is a company that is taking firm steps forward and growing rapidly in the electrical contracting sector. Since our establishment, we have adopted the principle of providing high quality service to our customers and ensuring excellence in our projects. We not only provide electrical contracting services, but also make a difference in the sector with renewable energy applications and consultancy services.",
 
"about-p-2":"With our young and dynamic team, we always prioritize our customer satisfaction-oriented service approach. We offer a wide range of solutions by combining our knowledge and experience in the field of electrical contracting with renewable energy and consultancy services. We have a structure that closely follows technology and constantly renews itself.",
"about-2":"Our Values",


"about-2.1":"Who are we?",
"about-2.1.1":"          Magma Group is a company that began making strong progress in the electrical contracting sector in 2019 and has been growing rapidly. Since its establishment, it has adopted a core principle of providing high-quality services to its clients and ensuring excellence in its projects. The company not only offers electrical contracting services but also aims to make a difference in renewable energy applications, project management, and consultancy services. In this way, it seeks to stand out in the industry by offering environmentally friendly and sustainable energy solutions.",
"about-2.2":"Our vision",
"about-2.2.1":"To be a leading company both nationally and internationally in the field of electrical contracting and renewable energy by making a difference through sustainable and innovative solutions. Our primary goal is to contribute to the future with environmentally friendly technologies, prioritizing customer satisfaction and high-quality service.",
"about-2.3":"Our Mission",
"about-2.3.1":"To provide solutions that best meet customer needs with our young and dynamic team; to combine our knowledge and experience with innovative approaches to deliver high-quality, reliable, and environmentally conscious projects. By offering sustainable services across a wide range of areas, from electrical contracting projects to renewable energy applications, we aim to further strengthen our trusted position in the industry.",
"about-n-1":"Our Services",
"about-n-1-1":"Electrical Contracting",
"about-n-1-2":"Consultancy",

"about-n-1-1-h": "Electrical Installation: ",
"about-n-1-1-p": "Electrical installation projects spanning a wide range, from industrial facilities to commercial buildings.",
"about-n-1-2-h": "Lighting Systems:",
"about-n-1-2-p": "Energy-efficient, aesthetic, and functional lighting solutions.",
"about-n-1-3-h": "Building Automation:",
"about-n-1-3-p": "Modern and secure living spaces with smart building systems.",
"about-n-2-1-h": "Solar Energy Systems:",
"about-n-2-1-p": "Rooftop and off-grid solar energy solutions..",
"about-n-2-2-h": "Energy Efficiency Projects:",
"about-n-2-2-p": "Optimizing energy consumption and sustainable solutions..",
"about-n-3-1-h": "Project Consultancy:",
"about-n-3-1-p": "Expert consultancy in the planning, design and implementation phases of projects.",
"about-n-3-2-h": "Energy Management:",
"about-n-3-2-p": "Consultancy on reducing energy costs and increasing efficiency.",
"about-n-3-3-h": "Technical Support and Training:",
"about-n-3-3-p": "Tailored technical support and training programs.",

"history":"History",
"history1":"Kartal Center Office",
"history1.1":"Center office is now operational in İstanbul, Kartal.",
"history2":"İzmit Technical Office",
"history2.1":"The project technical office is now operational in Izmit, Kocaeli.",
"history3":"Yalova Project Office",
"history3.1":"The project office was set up in the Çiftlikköy region.",
"history4":"Foundation",
"history4.1":"Magma Group Domestic and Foreign Trade. Ltd. Sti. Founded in 2019 in Istanbul.",

"etikilkelerimiz":"Our Ethical Principles",
"detaylıb":"Details",

"services1":"As Magma Group, we have been providing professional solutions in the electrical contracting sector since 2019. With our experienced team and innovative approach, we aim for the highest standards in electrical installation and infrastructure projects. We offer services across a wide range of areas, from industrial facilities to commercial buildings, residential projects, and public structures.",
"services2":"As Magma Group, we specialize in providing sustainable and environmentally friendly energy solutions. We carry out various projects in the field of renewable energy and offer our customers innovative solutions with high energy efficiency. With our experienced team, we always aim for the best results in solar energy, wind energy, and energy efficiency projects.",
"iletişime":"Contact us",
"iletişimform":"Contact Form",

"iform1":"Name",
"iform2":"Mail Adress",
"iform3":"Subject",
"iform4":"Message",
"iform5":"Send",

"adres1":"Center Office",
"adres2":"Technical Office",

"projelerimiz":"Our Projects",
"danışmanlık":"Consultancy",
"proje&danışmanlık" : "Project & Consultancy",

"all-right": " All Rights Reserved.",


    "successMessage": "Thank you! Your message has been delivered. We will contact you as soon as possible via the email address you provided.",
    "errorMessage": "Your message could not be delivered. Please try again. If the issue persists, you can contact us via email at info@magmagrup.com.tr.",

//*mithra project

    "projects-mithra-p": "The electrical installation work of the 'Mithra Technical Yarn Factory' with a construction area of 35,000 m² and an installed capacity of 10 MW, owned by Aksa Akrilik Kimya Sanayi A.Ş., a subsidiary of Akkök Holding located in the Çiftlikköy district of Yalova, is planned to be completed and handed over by the end of 2024",
    "projects-mithra-card-p1": "Elektrik Contracting",
    "projects-mithra-card-p2": "Aksa – Mithra Technical Yarn Factory",
    "projects-mithra-card-p3": "2024",
    "projects-mithra-card-p4": "Yalova, Çiftlikköy",

    "projects-mithra-li-1": "Public Address & Voice Evacuation Sys.",
    "projects-mithra-li-2": "Low Voltage Distribution System",
    "projects-mithra-li-3": "Lighting System",
    "projects-mithra-li-4": "Busbar Distribution System",
    "projects-mithra-li-5": "CCTV System",
    "projects-mithra-li-6": "Perimeter Lighting & Elect. Infrastructure",
    "projects-mithra-li-7": "Distribution, MCC & Comp. Panels",
    "projects-mithra-li-8": "Data/Network System",
    "projects-mithra-li-9": "Construction Site Mobilization",
    "projects-mithra-li-10": "Medium Voltage System",
    "projects-mithra-li-11": "Transformer Station",
    "projects-mithra-li-12": "UPS System",
    "projects-mithra-li-13": "Lighting Protection & Grounding",
    "projects-mithra-li-14": "Fire Detection & Alarm System",


    },
    "tr": {

        
        "proje&danışmanlık" : "Proje & Danışmanlık",
        //akkim
        "akkim-h1" : "Akkim Epoksi Tesisi ve Kontrol Binası",
        "akkim-p" : "Yalova’nın Çiftlikköy ilçesinde, Akkök Holding bünyesinde faaliyet gösteren Aksa Akrilik Kimya Sanayi A.Ş.’ye ait 35.000 m² inşaat alanına ve 10 MW kurulu güce sahip “Mithra Teknik İplik Fabrikası”nın elektrik tesisatı işinin 2024 yılı sonunda tamamlanması için çalışmalar devam etmektedir.",
        "akkim-li-1" : "Acil Anons ve Seslendirme Sistemi",
        "akkim-li-2" : "Alçak Gerilim Dağıtım Sistemi",
        "akkim-li-3" : "Ana Dağıtım Panosu",
        "akkim-li-4" : "Aydınlatma Sistemi",
        "akkim-li-5" : "Bina Otomasyon Sistemi",
        "akkim-li-6" : "CCTV Sistemi",
        "akkim-li-7" : "Çevre Aydınlatma ve Elek. Altyapısı",
        "akkim-li-8" : "Dağıtım,MCC ve Komp. Panoları",
        "akkim-li-9" : "Data/Network Sistemi",
        "akkim-li-10" : "Gazlı ve Köpüklü Söndürme Sistemi",
        "akkim-li-11" : "İnşaat Sahası Mobilizasyon",
        "akkim-li-12" : "Tv Sistemi",
        "akkim-li-13" : "UPS Sistemi",
        "akkim-li-14" : "Yangın Algılama ve İhbar Sistemi",
        "akkim-li-15" : "Yıldırımdan Koruma ve Topraklama",
        "akkim-card-p1" : "Elektrik Taahhüt",
        "akkim-card-p2" : "Akkim Epoksi Tesisi ve Kontrol Binası",
        "akkim-card-p3" : "2024",
        "akkim-card-p4" : "Yalova, Çiftlikköy",

        //sisecam
        "sisecam-h1" : "Şişecam Düzcam Tarsus Fabrikası Lojistik Merkezi",
        "sisecam-p" : "Mersin’in Tarsus ilçesinde yer alan, Türkiye Şişe ve Cam Fabrikaları A.Ş.'ye ait Düzcam Tarsus Fabrikası Lojistik Merkezi ve Kum Hazırlama Tesisi, 72.482 m² inşaat alanına sahiptir. 20 MW kurulu güce sahip olan tesisin elektrik tesisatı işleri yapılarak teslim edilecektir.",
        "sisecam-li-1" : "Acil Anons ve Seslendirme Sistemi",
        "sisecam-li-2" : "Alçak Gerilim Dağıtım Sistemi",
        "sisecam-li-3" : "Ana Dağıtım Panosu",
        "sisecam-li-4" : "Aydınlatma Sistemi",
        "sisecam-li-5" : "Bina Otomasyon Sistemi",
        "sisecam-li-6" : "Busbar Dağıtım Sistemi",
        "sisecam-li-7" : "CCTV Sistemi",
        "sisecam-li-8" : "Çevre Aydınlatma ve Elek. Altyapısı",
        "sisecam-li-9" : "Dağıtım,MCC ve Komp. Panoları",
        "sisecam-li-10" : "Data/Network Sistemi",
        "sisecam-li-11" : "Gazlı ve Köpüklü Söndürme Sistemi",
        "sisecam-li-12" : "İnşaat Sahası Mobilizasyon",
        "sisecam-li-13" : "Jeneratör Sistem",
        "sisecam-li-14" : "Kartlı Geçiş Sistemi",
        "sisecam-li-15" : "Kuvvet Busbarı Sistemi",
        "sisecam-card-p1" : "Elektrik Taahhüt",
        "sisecam-card-p2" : "Şişecam Düzcam Tarsus Fabrikası Lojistik Merkezi",
        "sisecam-card-p3" : "Devam Etmekte",
        "sisecam-card-p4" : "Mersin, Tarsus",

        //sertifikalar
        "sertifika" : "Sertifikalar",

        //danışmanlık
        "danişmanlik-h1" : "PROJE & DANIŞMANLIK",
        "danişmanlik-p" : "Elektrik proje tasarımı ve mühendislik çözümleri konusunda uzmanlaşmış bir firma olarak, yüksek kalite standartlarında hizmet sunarak elektrik altyapınızı güvenli, verimli ve sürdürülebilir bir yapıya kavuşturuyoruz. Elektrik proje çizimi, uygulama ve danışmanlık alanlarında geniş bir hizmet yelpazesi sunarak, projelerinizin her aşamasında sizinle beraber çalışıyoruz.",
        "danişmanlik-proje-h1" : "Proje",
        "danişmanlik-proje-p" : "Alçak ve orta gerilim, aydınlatma, güç dağıtımı, yangın algılama ve güvenlik sistemlerini içeren elektrik projelerinin teknik çizimlerini, ulusal ve uluslararası standartlara uygun şekilde hazırlıyoruz.",
        "danişmanlik-danişmanlik-h1" : "Danışmanlık",
        "danişmanlik-danişmanlik-p" : "Projelerinizde ihtiyaç duyduğunuz profesyonel danışmanlık hizmetlerini sunarak projelerinizin her aşamasında teknik destek sağlamaktadır. Projelerinizin planlama, tasarım, uygulama ve yönetim süreçlerinde ulusal ve uluslararası standartlara uygun, güvenilir ve verimli çözümler üretmekteyiz.",

//*mithra project
        "projects-mithra-card-p1": "Elektrik Taahhüt",
        "projects-mithra-card-p2": "Aksa – Mithra Teknik İplik Fabrikası",
        "projects-mithra-card-p3": "2024",
        "projects-mithra-card-p4": "Yalova, Çiftlikköy",

        "projects-mithra-li-1": "Acil Anons ve Seslendirme Sistemi",
        "projects-mithra-li-2": "Alçak Gerilim Dağıtım Sistemi",
        "projects-mithra-li-3": "Aydınlatma Sistemi",
        "projects-mithra-li-4": "Busbar Dağıtım Sistemi",
        "projects-mithra-li-5": "CCTV Sistemi",
        "projects-mithra-li-6": "Çevre Aydınlatma ve Elek. Altyapısı",
        "projects-mithra-li-7": "Dağıtım,MCC ve Komp. Panoları",
        "projects-mithra-li-8": "Data/Network Sistemi",
        "projects-mithra-li-9": "İnşaat Sahası Mobilizasyon",
        "projects-mithra-li-10": "Orta Gerilim Sistemi",
        "projects-mithra-li-11": "Trafo Merkezi",
        "projects-mithra-li-12": "UPS Sistemi",
        "projects-mithra-li-13": "Yıldırımdan Koruma ve Topraklama",
        "projects-mithra-li-14": "Yangın Algılama ve İhbar Sistemi",



        "projects-mithra-p": "Yalova’nın Çiftlikköy ilçesinde, Akkök Holding bünyesinde faaliyet gösteren Aksa Akrilik Kimya Sanayi A.Ş.’ye ait 35.000 m² inşaat alanına ve 10 MW kurulu güce sahip “Mithra Teknik İplik Fabrikası”nın elektrik tesisatı işinin 2024 yılı sonunda tamamlanması için çalışmalar devam etmektedir.",

        "successMessage": "Teşekkürler! Mesajınız iletildi, en kısa sürede girdiğiniz mail adresi üzerinden sizinle iletişime geçilecektir.",
        "errorMessage": "Mesajınız iletilemedi lütfen tekrar deneyiniz. Sorununuz devam ederse bizimle info@magmagrup.com.tr mail adresi üzerinden iletişime geçebilirsiniz",
        
        "all-right": " Her Hakkı Saklıdır. ",

        "danışmanlık":"Danışmanlık",
        "projelerimiz":"Projelerimiz",

        "adres1":"Merkez Ofis",
        "adres2":"Teknik Ofis",

        "iletişime":"Bizimle İletişime Geçin",
        "iletişimform":"İletişim Formu",

        "iform1":"İsim",
        "iform2":"Mail Adresi",
        "iform3":"Konu",
        "iform4":"Mesajınız",
        "iform5":"Gönder",

"services1":"Magma Grup olarak, 2019 yılından bu yana elektrik taahhüt alanında profesyonel çözümler sunmaktayız. Deneyimli ekibimiz ve yenilikçi yaklaşımımızla, elektrik tesisatı ve altyapı projelerinde en yüksek standartları hedefliyoruz. Endüstriyel tesislerden ticari binalara, konut projelerinden kamu yapılarına kadar geniş bir yelpazede hizmet veriyoruz.",
"services2":"Magma Grup olarak, sürdürülebilir ve çevre dostu enerji çözümleri sunma konusunda uzmanız. Yenilenebilir enerji alanında çeşitli projeler gerçekleştiriyor ve müşterilerimize enerji verimliliği yüksek, yenilikçi çözümler sunuyoruz. Güneş enerjisi, rüzgar enerjisi ve enerji verimliliği projelerinde deneyimli ekibimizle her zaman en iyi sonuçları hedefliyoruz.",

"detaylıb":"Detaylı Bilgi",
"etikilkelerimiz":"Etik İlkelerimiz",
 //about
 "history":"Tarihçemiz",
 "history1":"Kartal Merkez Ofis",
 "history1.1":"Kartal Merkez Ofis",
 "history1.1":"İstanbul, Kartal ilçesinde Merkez ofis faaliyete geçti.",
 "history2":"İzmit Teknik Ofis",
 "history2.1":"Kocaeli, İzmit ilçesinde proje teknik ofis faaliyete geçti.",
 "history3":"Yalova Proje Ofisi",
 "history3.1":"Proje ofisinin kurulumu Çiftlikköy bölgesinde gerçekleştirildi.",
 "history4":"Kuruluş",
 "history4.1":"Magma Grup İç ve Dış Tic. Ltd. Şti. 2019 yılında İstanbul'da kuruldu.",

 "about-n-1-2":"Danışmanlık Hizmetleri",
 "about-n-1-1":"Elektrik Taahhüt Hizmetleri",
 "about-n-1":"Neler Yapıyoruz",
 "about-p-1":"2019 yılında kurulan Magma Grup, elektrik taahhüt sektöründe sağlam adımlarla ilerleyen ve hızla büyüyen bir şirkettir. Kuruluşumuzdan bu yana, müşterilerimize yüksek kaliteli hizmet sunmayı ve projelerimizde mükemmelliği sağlamayı ilke edindik. Sadece elektrik taahhüt hizmetleri sunmakla kalmayıp, aynı zamanda yenilenebilir enerji uygulamaları ve danışmanlık hizmetleriyle de sektörde fark yaratmaktayız.",
 
 "about-p-2":"Genç ve dinamik ekibimizle, müşteri memnuniyeti odaklı hizmet anlayışımızı her zaman ön planda tutuyoruz. Elektrik taahhüt alanındaki bilgi birikimimizi ve tecrübemizi, yenilenebilir enerji ve danışmanlık hizmetleriyle birleştirerek, geniş bir yelpazede çözümler sunuyoruz. Teknolojiyi yakından takip eden ve sürekli kendini yenileyen bir yapıya sahibiz.",
 "about-2":"Değerlerimiz",


 "about-2.1":"Biz Kimiz?",

 "about-2.1.1":"Magma Grup olarak, yüksek kaliteli hizmetleri sunarak, müşterilerimizin projelerinde güvenli, verimli ve yenilikçi çözümler sağlamayı hedefliyoruz. Teknolojik gelişmeleri yakından takip ederek, sürdürülebilir enerji kaynaklarını etkin bir şekilde kullanarak, sektördeki en yüksek standartları karşılamayı amaçlıyoruz. Profesyonel ve deneyimli ekibimizle, müşteri memnuniyetini en üst düzeyde tutarak, her projeyi zamanında ve bütçe dahilinde tamamlamayı taahhüt ediyoruz.",

 "about-2.2":"Vizyonumuz",

 "about-2.2.1":"Magma Grup olarak, yüksek kaliteli hizmetleri sunarak, müşterilerimizin projelerinde güvenli, verimli ve yenilikçi çözümler sağlamayı hedefliyoruz. Teknolojik gelişmeleri yakından takip ederek, sürdürülebilir enerji kaynaklarını etkin bir şekilde kullanarak, sektördeki en yüksek standartları karşılamayı amaçlıyoruz. Profesyonel ve deneyimli ekibimizle, müşteri memnuniyetini en üst düzeyde tutarak, her projeyi zamanında ve bütçe dahilinde tamamlamayı taahhüt ediyoruz.",

 "about-2.3":"Misyonumuz",

 "about-2.3.1":"Magma Grup olarak, elektrik sektöründe lider ve yenilikçi bir şirket olmayı hedefliyoruz. Sektördeki en ileri teknolojileri ve yöntemleri kullanarak, geleceğin enerji çözümlerini bugünden sunmak, sürdürülebilir ve çevre dostu projelerle topluma katkıda bulunmak istiyoruz. Amacımız, tanınan ve tercih edilen bir marka haline gelerek, her geçen gün daha geniş bir müşteri kitlesine ulaşmak ve sektördeki en güvenilir isimlerden biri olmaktır",


        "about-n-1-1-h": "Elektrik Tesisatı: ",
        "about-n-1-1-p": "Endüstriyel tesislerden ticari binalara kadar geniş kapsamlı elektrik tesisat projeleri.",
        "about-n-1-2-h": "Aydınlatma Sistemleri: ",
        "about-n-1-2-p": "Enerji verimliliği yüksek, estetik ve fonksiyonel aydınlatma çözümleri.",
        "about-n-1-3-h": "Bina Otomasyonu:",
        "about-n-1-3-p": "Akıllı bina sistemleri ile modern ve güvenli yaşam alanları.",
        "about-n-2-1-h": "Güneş Enerjisi Sistemleri: ",
        "about-n-2-1-p": "Çatı ve arazi tipi güneş enerjisi çözümleri.",
        "about-n-2-2-h": "Enerji Verimliliği Projeleri:",
        "about-n-2-2-p": "Enerji tüketiminin optimize edilmesi ve sürdürülebilir çözümler.",
        "about-n-3-1-h": "Proje Danışmanlığı:",
        "about-n-3-1-p": "Projelerin planlama, tasarım ve uygulama aşamalarında uzman danışmanlık.",
        "about-n-3-2-h": "Enerji Yönetimi:",
        "about-n-3-2-p": "Enerji maliyetlerini düşürme ve verimliliği artırma konularında danışmanlık.",
        "about-n-3-3-h": "Teknik Destek ve Eğitim:",
        "about-n-3-3-p": "Müşterilere özel teknik destek ve eğitim programları.",





        //home
        "navHome": "Anasayfa",
        "navProjects": "Projelerimiz",
        "navAbout": "Hakkımızda",
        "navServices": "Hizmetlerimiz",
        "navContact": "İletişim",
        "proje": "Proje",
        //elec
        "elec-header-h": "Elektrik Taahhüt",
        "elec-header-p": "Magma Grup olarak, 2019 yılından bu yana elektrik taahhüt alanında profesyonel çözümler sunmaktayız. Deneyimli ekibimiz ve yenilikçi yaklaşımımızla, elektrik tesisatı ve altyapı projelerinde en yüksek standartları hedefliyoruz. Endüstriyel tesislerden ticari binalara, konut projelerinden kamu yapılarında kadar geniş bir yelpazede hizmet veriyoruz.",
        //elec-1
        "elec-1-h": "1. Endüstriyel Elektrik Tesisatı",
        "elec-1-p": "Endüstriyel tesislerde güvenli, verimli ve sürdürülebilir elektrik çözümleri sunuyoruz. Hizmetlerimiz arasında enerji dağıtım sistemleri, motor kontrol merkezleri, otomasyon sistemleri ve özel proses elektrik tesisatları bulunmaktadır.",
        "elec-1-li-1-h": "Enerji Dağıtım Sistemleri: ",
        "elec-1-li-1-p": "Fabrika ve üretim tesislerinde enerji dağıtımının güvenli ve verimli bir şekilde yapılması.",
        "elec-1-li-2-h": "Motor Kontrol Merkezleri: ",
        "elec-1-li-2-p": "Endüstriyel motorların kontrol ve otomasyonu için çözümler.",
        "elec-1-li-3-h": "Otomasyon Sistemleri: ",
        "elec-1-li-3-p": "Üretim süreçlerinin otomasyonu ve verimliliğin artırılması.",
        "elec-1-li-4-h": "Proses Elektrik Tesisatları: ",
        "elec-1-li-4-p": "Özel üretim süreçlerine uygun elektrik tesisatları.",
        //elec-2
        "elec-2-h": "2. Ticari Binalar ve Ofisler",
        "elec-2-p": "Ticari binalar, ofisler ve alışveriş merkezleri için komple elektrik çözümleri sunuyoruz. Aydınlatma sistemleri, enerji yönetimi, güvenlik sistemleri ve daha fazlasını kapsayan hizmetlerimizle, ticari mekanların ihtiyaçlarını karşılıyoruz.",
        "elec-2-li-1-h": "Aydınlatma Sistemleri: ",
        "elec-2-li-1-p": "Enerji verimli ve estetik aydınlatma çözümleri.",
        "elec-2-li-2-h": "Enerji Yönetimi: ",
        "elec-2-li-2-p": "Ticari binalarda enerji tüketiminin optimizasyonu.",
        "elec-2-li-3-h": "Güvenlik Sistemleri: ",
        "elec-2-li-3-p": "Yangın alarm sistemleri, CCTV ve erişim kontrol sistemleri.",
        "elec-2-li-4-h": "Bina Otomasyonu: ",
        "elec-2-li-4-p": "Akıllı bina sistemleri ile modern ve verimli ofis ortamları.",
        //elec-3
        "elec-3-h": "3. Konut Projeleri",
        "elec-3-p": "Konut projeleri için kapsamlı elektrik tesisat hizmetleri sunuyoruz. Apartmanlar, villa siteleri ve bireysel konutlar için güvenli ve modern elektrik çözümleri sağlıyoruz.",
        "elec-3-li-1-h": "Temel Elektrik Tesisatı: ",
        "elec-3-li-1-p": "Yeni konut projeleri için tam kapsamlı elektrik tesisatı.",
        "elec-3-li-2-h": "Aydınlatma ve Priz Tesisatı: ",
        "elec-3-li-2-p": "Konut içi aydınlatma ve priz yerleşimi.",
        "elec-3-li-3-h": "Akıllı Ev Sistemleri: ",
        "elec-3-li-3-p": "Akıllı ev teknolojileri ile yaşam alanlarının modernizasyonu.",
        "elec-3-li-4-h": "Güvenlik Sistemleri: ",
        "elec-3-li-4-p": "Ev güvenliği için alarm ve CCTV sistemleri.",
        //elec-4
        "elec-4-h": "4. Kamu ve Eğitim Yapıları",
        "elec-4-p": "Kamu binaları, okullar, hastaneler ve diğer eğitim yapıları için elektrik taahhüt hizmetleri sunuyoruz. Bu yapılarda güvenlik, verimlilik ve kullanıcı dostu çözümler önceliğimizdir.",
        "elec-4-li-1-h": "Aydınlatma Sistemleri: ",
        "elec-4-li-1-p": "Kamu ve eğitim yapıları için uygun aydınlatma çözümleri.",
        "elec-4-li-2-h": "Enerji Dağıtım ve Yönetimi: ",
        "elec-4-li-2-p": "Kamu binalarında enerji dağıtımı ve yönetimi.",
        "elec-4-li-3-h": "Acil Durum Sistemleri: ",
        "elec-4-li-3-p": "Yangın alarmı, acil çıkış aydınlatmaları ve yedek güç sistemleri.",
        "elec-4-li-4-h": "IT ve İletişim Altyapısı: ",
        "elec-4-li-4-p": "Eğitim ve kamu binaları için IT altyapı çözümleri.",
        //elec-5
        "elec-5-h": "Zayıf Akım Sistemleri",
        "elec-5-li-1": "Seslendirme ve Acil Anons Sistemi",
        "elec-5-li-2": "Yangın Algılama ve İhbar Sistemi",
        "elec-5-li-3": "Kartlı Geçiş Sistemi",
        "elec-5-li-4": "TV/IPTV/SMATV Sistemi",
        "elec-5-li-5": "Data Sistemi",
        "elec-5-li-6": "Otopark Yönlendirme Sistemi",
        "elec-5-li-7": "Merkezi Saat Sistemi",
        "elec-5-li-8": "Telsiz Sistemi",
        "elec-5-li-9": "SCADA",
        //elec-6
        "elec-6-h": "Alçak Gerilim Sistemleri",
        "elec-6-li-1": "Busbar Dağıtım Sistemi",
        "elec-6-li-2": "Dağıtım, MCC ve Kompanzasyon Panoları",
        "elec-6-li-3": "Kablo Taşıma Sistemi",
        "elec-6-li-4": "Aydınlatma Armatür Tesisatları",
        "elec-6-li-5": "Aydınlatma - İklimlendirme Otomasyonu",
        "elec-6-li-6": "UPS Tesisatları ve Bina Otomasyonu",
        "elec-6-li-7": "Jeneratör Sistemi",
        "elec-6-li-8": "Yıldırımdan Korunma ve Topraklama",
        "elec-6-li-9": "SCADA ve Enerji İzleme Otomasyonu",
        //elec-7
        "elec-7-h": "Orta Gerilim Sistemleri",
        "elec-7-li-1": "O.G. Enerji Temini ve Dağıtımı",
        "elec-7-li-2": "Transformatör ve O.G. Temini ve Tesisat İşleri",
        "elec-7-li-3": "Test ve Devreye Alma İşleri",
        "elec-7-li-4": "Enerji Müsaade Belgesi Temini ve Elektrik İdaresi Kabul İşleri",
        //renew
        "renew-header-h": "Yenilenebilir Enerji",
        "renew-header-p": "Magma Grup olarak, sürdürülebilir ve çevre dostu enerji çözümleri sunma konusunda uzmanız. Yenilenebilir enerji alanında çeşitli projeler gerçekleştiriyor ve müşterilerimize enerji verimliliği yüksek, yenilikçi çözümler sunuyoruz. Güneş enerjisi, rüzgar enerjisi ve enerji verimliliği projelerinde deneyimli ekibimizle her zaman en iyi sonuçları hedefliyoruz.",
        //renew-1
        "renew-1-h": "1. Güneş Enerjisi Sistemleri",
        "renew-1-p": "Güneş enerjisi, temiz ve tükenmez bir enerji kaynağıdır. Magma Grup olarak, çeşitli ölçeklerde güneş enerjisi sistemleri kurarak müşterilerimizin enerji ihtiyaçlarını karşılıyoruz.",
        "renew-1-li-1-h": "Çatı Tipi Güneş Enerjisi Sistemleri: ",
        "renew-1-li-1-p": "Konutlar, ticari binalar ve endüstriyel tesisler için çatı üzerine kurulan fotovoltaik paneller.",
        "renew-1-li-2-h": "Arazi Tipi Güneş Enerjisi Sistemleri: ",
        "renew-1-li-2-p": "Büyük ölçekli enerji üretimi için geniş arazilere kurulan güneş enerji santralleri.",
        "renew-1-li-3-h": "Enerji Depolama Sistemleri: ",
        "renew-1-li-3-p": "Güneş enerjisi sistemlerine entegre edilen bataryalar ile enerji depolama ve yönetimi.",
        "renew-1-li-4-h": "Hibrit Sistemler: ",
        "renew-1-li-4-p": "Hem güneş enerjisi hem de şebeke enerjisini kullanarak kesintisiz enerji sağlayan hibrit çözümler.",
        //renew-2
        "renew-2-h": "2. Enerji Verimliliği Projeleri",
        "renew-2-p": "Enerji verimliliği, hem maliyetleri düşürmek hem de çevresel etkileri azaltmak için kritik öneme sahiptir. Magma Grup olarak, enerji verimliliği projeleriyle müşterilerimize daha sürdürülebilir çözümler sunuyoruz.",
        "renew-2-li-1-h": "Enerji Denetimi: ",
        "renew-2-li-1-p": "Binalar ve tesislerde enerji tüketiminin analiz edilmesi ve verimlilik fırsatlarının belirlenmesi.",
        "renew-2-li-2-h": "Enerji Yönetimi Sistemleri: ",
        "renew-2-li-2-p": "Enerji tüketimini izleme, yönetme ve optimize etme çözümleri.",
        "renew-2-li-3-h": "Verimli Aydınlatma Sistemleri: ",
        "renew-2-li-3-p": "Enerji tasarrufu sağlayan LED aydınlatma ve akıllı aydınlatma sistemleri.",
        "renew-2-li-4-h": "İzolasyon ve Isı Geri Kazanım: ",
        "renew-2-li-4-p": "Binalarda enerji kaybını önlemek için izolasyon çözümleri ve ısı geri kazanım sistemleri.",
        //renew-3
        "renew-3-h": "Güneş Enerjisi Sistemleri",
        "renew-3-li-1": "Çatı Tipi Güneş Enerjisi Sistemi",
        "renew-3-li-2": "Arazi Tipi Güneş Enerjisi Sistemi",
        "renew-3-li-3": "Enerji Depolama Sistemi",
        "renew-3-li-4": "Hibrit Sistemler",
        //renew-4
        "renew-4-h": "Enerji Verimliliği Projeleri",
        "renew-4-li-1": "Enerji Denetimi",
        "renew-4-li-2": "Enerji Yönetimi Sistemleri",
        "renew-4-li-3": "Verimli Aydınlatma Sistemleri",
        "renew-4-li-4": "İzolasyon ve Isı Geri Kazanım",

        //projects
        "projects-h1": "PROJELER",
        "projects-p1": "TCMB Ümraniye Ek Yerleşkesi",
        "projects-p2": "Dowaksa-Linde Yol Aydınlatması",
        "projects-p3": "Dowaksa Karbon Elyaf Fabrikası Kapasite Artırım Projesi",
        "projects-p4": "ÇOSB Çevre Aydınlatma ve Kamera Altyapısı",
        "projects-p5": "Aksafil Akrilik İplik Fabrikası ve Mamul Ambarı",
        "projects-p6": "Akcennet Rekreasyon Alanı Aydınlatması",
        "projects-p7": "Arçelik Çamaşır Makinesi Fabrikası",
        "projects-p8": "Aksa Tır Parkı",
        "projects-p9": "Akbatı AVM Ges",
        "projects-p10": "Akasya AVM Ges Projesi",
        "projects-p11": "Mithra Teknik İplik Fabrikrası",
        "projects-p12": "Şişecam Düzcam Tarsus Fabrikası Lojistik Merkezi",
        "projects-p13": "Akkim Epoksi Tesisi ve Kontrol Binası",
        "projects-t": "Taahhüt",
        "projects-y": "Yenilenebilir Enerji",
        "projects-photos-h": "Fotoğraflar",
        //projects-tcmb
        "projects-tcmb-header": "TCMB Ümraniye Ek Yerleşkesi",
        "projects-tcmb-p": "İstanbul’un Ümraniye ilçesinde 2019 yılının Ekim ayında başlanılan proje 2020 yılının Mart ayında tamamlanmıştır. Yaklaşık 21.000 m² kapalı alana sahip yapı 13’ü normal, 2’si otopark olmak üzere toplam 15 kattır.",
        "projects-tcmb-h-1": "Proje Detayı",
        "projects-tcmb-h-2": "Yapılan İşler:",
        "projects-tcmb-li-1": "Aydınlatma Sistemi",
        "projects-tcmb-li-2": "Alçak Gerilim Dağıtım Sistemi",
        "projects-tcmb-li-3": "Yangın Algılama ve İhbar Sistemi",
        "projects-tcmb-li-4": "Acil Anons ve Seslendirme Sistemi",
        "projects-tcmb-li-5": "Kartlı Geçiş Sistemi",
        "projects-tcmb-li-6": "Data/Network Sistemi",
        "projects-tcmb-li-7": "Busbar Dağıtım Sistemi",
        "projects-tcmb-li-8": "Dağıtım, MCC ve Kompanzasyon Panoları",
        "projects-tcmb-li-9": "Bina Otomasyon Sistemi",
        "projects-tcmb-li-10": "UPS Sistemi",
        "projects-tcmb-li-11": "Jeneratör Sistemi",
        "projects-tcmb-li-12": "Yıldırımdan Koruma ve Topraklama",
        "projects-tcmb-li-13": "Orta Gerilim Sistemi",
        "projects-tcmb-card-h1": "Proje: ",
        "projects-tcmb-card-h2": "Proje Adı: ",
        "projects-tcmb-card-h3": "Yıl: ",
        "projects-tcmb-card-h4": "Adres: ",
        "projects-tcmb-card-p1": "Elektrik Taahhüt",
        "projects-tcmb-card-p2": "Türkiye Cumhuriyet Merkez Bankası – Ümraniye Ek Yerleşkesi",
        "projects-tcmb-card-p3": "2019",
        "projects-tcmb-card-p4": "İstanbul, Ümraniye",
        //projects-linde
        "projects-linde-header": "Dowaksa-Linde Yol Aydınlatması",
        "projects-linde-p": "Yalova’nın Çiftlikköy ilçesinde yer alan Akkök Holding bünyesinde bulunan Dowaksa yerleşkesi Linde yolunun aydınlatması 2021 yılında yapılarak teslim edilmiştir.",
        "projects-linde-li-1": "Poligon Tipi Aydınlatma Direği Uygulaması",
        "projects-linde-card-p1": "Elektrik Taahhüt",
        "projects-linde-card-p2": "Dowaksa-Linde Yol Aydınlatması",
        "projects-linde-card-p3": "2021",
        "projects-linde-card-p4": "Yalova, Çiftlikköy",
        //projects-dowaksa
        "projects-dowaksa-header": "Dowaksa Karbon Elyaf Fabrikası Kapasite Artırım Projesi",
        "projects-dowaksa-p": "Yalova’nın Çiftlikköy ilçesinde yer alan Akkök Holding bünyesinde bulunan Dowaksa İleri Kompozit Malzemeler Ltd. Şti.’ye ait Karbon Elyaf Kompozit Malzeme üretim tesisi kapasite artırım projesi elektrik tesisatı yapılarak 2024 yılında teslim edildi. 117.000 m² alan üzerine kurulan tesis 18 bağımsız yapıdan oluşmaktadır.",
        "projects-dowaksa-li-1": "Alçak Gerilim Dağıtım Sistemi",
        "projects-dowaksa-li-2": "Dağıtım Panoları",
        "projects-dowaksa-li-3": "Yangın Algılama ve İhbar Sistemi",
        "projects-dowaksa-li-4": "Acil Anons ve Seslendirme Sistemi",
        "projects-dowaksa-li-5": "Aydınlatma Sistemi",
        "projects-dowaksa-li-6": "Yıldırımdan Koruma ve Topraklama",
        "projects-dowaksa-li-7": "CCTV Sistemi",
        "projects-dowaksa-li-8": "Gazlı ve Köpüklü Söndürme Algılama",
        "projects-dowaksa-li-9": "Çevre Aydınlatma ve Altyapı",
        "projects-dowaksa-li-10": "Data / Network Sistemi",
        "projects-dowaksa-card-p1": "Elektrik Taahhüt",
        "projects-dowaksa-card-p2": "Dowaksa – Karbon Elyaf Fabrikası Kapasite Artırım Projesi",
        "projects-dowaksa-card-p3": "2024",
        "projects-dowaksa-card-p4": "Yalova, Çiftlikköy",
        //projects-cosb
        "projects-cosb-header": "ÇOSB Çevre Aydınlatma ve Kamera Altyapısı",
        "projects-cosb-p": " Tekirdağ’ın Kapaklı ilçesinde yer alan Çerkezköy Organize Sanayi Bölgesi içerisinde ki sokakların ve İleri Biyoloji Arıtma Tesisi’nin çevre aydınlatma ve güvenlik kamerası alt yapısı 2021 yılında yapılarak teslim edilmiştir.",
        "projects-cosb-li-1": "Sokak Aydınlatma Direkleri",
        "projects-cosb-li-2": "Kamera Direkleri",
        "projects-cosb-li-3": "UPS Sistemi",
        "projects-cosb-card-p1": "Elektrik Taahhüt",
        "projects-cosb-card-p2": "Çerkezköy Organize Sanayi Bölgesi – Çevre Aydınlatma ve Kamera Altyapısı",
        "projects-cosb-card-p3": "2021",
        "projects-cosb-card-p4": "Tekirdağ, Kapaklı",
        //projects-aksafil
        "projects-aksafil-header": "Aksafil Akrilik İplik Fabrikası ve Mamul Ambarı",
        "projects-aksafil-p": "Yalova’nın Çiftlikköy ilçesinde yer alan Akkök Holding bünyesinde bulunan Aksa Akrilik Kimya Sanayi A.Ş.’ye ait 28.716 m² inşaat alanı olan, 8 MW kurulu güce sahip “Airjet Akrilik İplik Fabrikası ve Hammadde Ambar Deposu” elektrik tesisatı işi 2023 yılında tamamlanarak teslim edilmiştir.",
        "projects-aksafil-li-1": "Aydınlatma Sistemi",
        "projects-aksafil-li-2": "Alçak Gerilim Dağıtım Sistemi",
        "projects-aksafil-li-3": "Yangın Algılama ve İhbar Sistemi",
        "projects-aksafil-li-4": "Acil Anons ve Seslendirme Sistemi",
        "projects-aksafil-li-5": "Data/Network Sistemi",
        "projects-aksafil-li-6": "Busbar Dağıtım Sistemi",
        "projects-aksafil-li-7": "Dağıtım Panoları",
        "projects-aksafil-li-8": "Yıldırımdan Koruma ve Topraklama",
        "projects-aksafil-li-9": "Orta Gerilim Sistemi",
        "projects-aksafil-li-10": "Saha Mobilizasyon",
        "projects-aksafil-card-p1": "Elektrik Taahhüt",
        "projects-aksafil-card-p2": "Aksa – Airjet İplik Fabrikası ve Hammadde Ambar Deposu",
        "projects-aksafil-card-p3": "2023",
        "projects-aksafil-card-p4": "Yalova, Çiftlikköy",
        //projects-akcennet
        "projects-akcennet-header": "Akcennet Rekreasyon Alanı Aydınlatması",
        "projects-akcennet-p": "Yalova’nın Çiftlikköy ilçesinde yer alan Akkök Holding bünyesinde bulunan Aksa Akrilik Elyaf Fabrikası’na ait rekreasyon alanının çevre aydınlatması işi 2020 yılında yapılarak teslim edilmiştir.",
        "projects-akcennet-li-1": "Dekoratif Aydınlatma Direkleri",
        "projects-akcennet-li-2": "Bollard Dekoratif Aydınlatma",
        "projects-akcennet-li-3": "Kombinasyon Priz Sistemi",
        "projects-akcennet-li-4": "Poligon Aydınlatma Direkleri",
        "projects-akcennet-card-p1": "Elektrik Taahhüt",
        "projects-akcennet-card-p2": "Aksa – Akcennet Rekreasyon Alanı Aydınlatması",
        "projects-akcennet-card-p3": "2020",
        "projects-akcennet-card-p4": "Yalova, Çiftlikköy",
        //projects-arcelik
        "projects-arcelik-header": "Arçelik Çamaşır Makinesi Fabrikası",
        "projects-arcelik-p": "Manisa’nın Yunus Emre ilçesinde yer alan Manisa Organize Sanayi Bölgesinde bulunan Arçelik Çamaşır Makinesi Fabrikası’nın 20 MW (8×2,5MW) gücünde orta gerilim elektrik altyapı işi yapılarak 2024 yılında teslim edildi.",
        "projects-arcelik-li-1": "Trafo Merkezi",
        "projects-arcelik-li-2": "Kuvvet Busbar Sistemi",
        "projects-arcelik-li-3": "Yangın Algılama ve İhbar Sistemi",
        "projects-arcelik-li-4": "Acil Anons ve Seslendirme Sistemi",
        "projects-arcelik-li-5": "Ana Dağıtım Panosu",
        "projects-arcelik-card-p1": "Elektrik Taahhüt",
        "projects-arcelik-card-p2": "Arçelik – Çamaşır Makinesi Fabrikası Elektrik Orta Gerilim Altyapı",
        "projects-arcelik-card-p3": "2024",
        "projects-arcelik-card-p4": "Manisa, Yunus Emre",
        //projects-aksa
        "projects-aksa-header": "Aksa Tır Parkı",
        "projects-aksa-p": "Yalova’nın Çiftlikköy ilçesinde yer alan Akkök Holding bünyesinde bulunan tır parkının elektrik tesisatı 2022 yılında yapılarak teslim edilmiştir.",
        "projects-aksa-li-1": "Poligon Tipi Direk Montajı",
        "projects-aksa-li-2": "Aydınlatma Montajı",
        "projects-aksa-li-3": "Kamera Alt Yapısı",
        "projects-aksa-li-4": "Kombinasyon Priz Tesisatı",
        "projects-aksa-card-p1": "Elektrik Taahhüt",
        "projects-aksa-card-p2": "Aksa – Tır Parkı Aydınlatması",
        "projects-aksa-card-p3": "2022",
        "projects-aksa-card-p4": "Yalova, Çiftlikköy",
        //projects-akbati
        "projects-akbati-header": "Akbatı AVM Ges",
        "projects-akbati-p": "İstanbul’un Esenyurt ilçesinde yer alan Akbatı AVM’nin çatısına güneş enerji santrali kurularak 2023 yılında teslim edildi.",
        "projects-akbati-card-h1": "Kapasite: ",
        "projects-akbati-card-p1-1": "Yenilenebilir Enerji",
        "projects-akbati-card-p1-2": "Güneş Enerji Santrali",
        "projects-akbati-card-p2": "Akbatı AVM Çatı Ges",
        "projects-akbati-card-p3": "915kWp/750kWe",
        "projects-akbati-card-p4": "2023",
        "projects-akbati-card-p5": "İstanbul, Esenyurt",
        //projects-akasya
        "projects-akasya-header": "Akasya AVM Ges Projesi",
        "projects-akasya-p": "İstanbul’un Kadıköy ilçesinde yer alan Akasya AVM’nin çatısına güneş enerji santrali kurularak 2023 yılında teslim edildi.",
        "projects-akasya-card-h1": "Kapasite: ",
        "projects-akasya-card-p1-1": "Yenilenebilir Enerji",
        "projects-akasya-card-p1-2": "Güneş Enerji Santrali",
        "projects-akasya-card-p2": "Akasya AVM Çatı Ges",
        "projects-akasya-card-p3": "773kWp/750kWe",
        "projects-akasya-card-p4": "2023",
        "projects-akasya-card-p5": "İstanbul, Kadıköy",

        "services": "HİZMETLERİMİZ",



        //furkan1
        "why":"Neden",
        "whyuse1": "Uzmanlık Ve Deneyim",
        "whyuse1.1": "Deneyimli ekibimizle, her projenin benzersiz ihtiyaçlarına uygun çözümler üretiyoruz. Geniş bilgi birikimimiz ve projelerdeki uzmanlığımız, müşterilerimize en iyi sonuçları sunmamızı sağlar.",
        "whyuse2": "Teknolojik Yenilikler",
        "whyuse2.1":"Sektördeki en son teknolojileri kullanarak, enerji verimliliği yüksek ve uzun ömürlü sistemler tasarlıyoruz. Yenilikçi yaklaşımımızla, projelerimizin performansını ve sürdürülebilirliğini artırıyoruz.",
        "whyuse3": "Çevre Dostu Çözümler",
        "whyuse3.1":"Çevre dostu ve sürdürülebilir enerji çözümleri sunmayı taahhüt ediyoruz. Yenilenebilir enerji projelerimizle, karbon ayak izini azaltmayı ve çevresel etkileri en aza indirmeyi hedefliyoruz.",
        "whyuse4": "Müşteri Memnuniyeti",
        "whyuse4.1": "Müşteri memnuniyeti, işimizin merkezinde yer alır. Projelerin her aşamasında müşterilerimizle yakın iş birliği içinde çalışarak, onların beklentilerini aşmayı amaçlıyoruz.",
        "whyuse5": "Kalite ve Güvenlik",
        "whyuse5.1": "Tüm projelerimizde en yüksek kalite ve güvenlik standartlarını uyguluyoruz. Kullanılan malzemelerden işçilik detaylarına kadar her aşamada kalite kontrol prosedürlerimize bağlı kalıyoruz.",
        "whyuse6": "İş, İşçi Sağlığı ve Güvenliği",
        "whyuse6.1": "İş, işçi sağlığı ve güvenliği konularında en yüksek standartları benimsemekteyiz. Tüm projelerimizde çalışanlarımızın ve paydaşlarımızın güvenliğini sağlamak birincil önceliğimizdir.",
        "referances":"Referanslarımız",
        "about": "HAKKIMIZDA",
        "about1": "    Magma Grup olarak işlerimizi büyütürken uyma ve uyulması konusunda yönlendirici olma sorumluluğunda etik kurallarımız vardır. İnsan, toplum ve doğa merkezli çalışma prensibiyle yolumuza devam ediyoruz. İlişkilerimizde şeffaf, adil ve hesap verebilir olmayı benimsiyoruz. Aldığımız kararlarda “dürüstlük, doğruluk ve saygı” temel değerlerimizdir. Bu ilkeler yöneticilerimize, çalışanlarımıza ve iş ortaklarımıza yol gösterici olması için oluşturulmuştur. ",
        "etik":"Etik İlkeler",
        "etik1":"1. İnsan Haklarına Saygı ve Ayrımcılığın Önlenmesi",
        "etik2":"2. Hukuka Uyum – KVKK – Bilgilerin Gizliliği",
        "etik3":"3. İş Sağlığı ve Güvenliği",
        "etik4":"4. Çevrenin Korunması",
        "etik5":"5. Paydaşlarla İlişkiler",

        "buton":"Hakkımızda",
        "buton1":"Firma Ünvanı",
        "buton2":"Vergi Dairesi:",
        "buton3":"Vergi Numarası:",
        "buton4":"Ticaret Sicil Numarası:",
        "buton5":"Mersis Numarası:",
        "buton6":"MERKEZ OFİS",
        "buton7":"TEKNİK OFİS",
        "buton8":"TELEFON",
        "buton9":"E-POSTA",



        "etik1.1":"İşe alımlarda tek kıstasımız işe uygunluk vasfıdır. Cinsiyet, dil, din, ırk, renk, yaş, gözetilmez.",
        "etik1.2":"Adil ve rekabetçi ücret politikaları, etkin ve objektif performans değerlendirme sistemi ve uygulamaları ile başarıyı ödüllendirerek şirkete olan bağlığını artırmayı hedeflenir.",
        "etik1.3":"Çalışanlarımızın eğitilmesi ve geliştirilmesi için imkân sağlanır.",
        "etik1.4":"Şeffaf ve karşılıklı saygıyı teşvik eden bir çalışma ortamı yaratılır.",
        "etik1.5":"Ayrımcılığın, şiddetin ve tacizin hiçbir türüne tolerans gösterilmez.",
        "etik1.6":"Çalışanlarımıza temiz, sağlıklı ve güvenli çalışma koşulları sağlanır.",
        "etik1.7":"Çocuk işçiliğine ve zorla çalıştırmaya karşı tolerans göstermeyiz.",

        "etik2.1":"İş yaptığımız her yerde, hukuka uygun hareket eder, gerekli hallerde yetkili mercilere danışılır.",
        "etik2.2":"Fikri ve sınai mülkiyet haklarına saygılı olmak bu alandaki temel prensiplerimizdir.",
        "etik2.3":"Kişisel verilerin işlenmesinde yasal düzenlemelere uygun davranır, gerekli önlemleri alırız. Bu kapsamda, tabi olduğumuz yerel ve uluslararası mevzuata ve kişisel verilerin işlenmesinde belirlenen ilkelere her koşulda uygun hareket ederiz.",
        "etik2.4":"Tüm ticari faaliyetlerimizi ve kayıtlarımızı ve üçüncü taraflarla yapılan anlaşmaların mevzuata, Etik İlkeleri’mize ve politikalarımıza uygun, açık ve anlaşılır olduğundan emin oluruz.",
        "etik2.5":"Çalışanlarımız, doğrudan, dolaylı olarak veya üçüncü kişiler aracılığı ile hiçbir kişi ya da kuruluştan, rüşvet, herhangi bir menfaat, kolaylaştırıcı ödeme kabul edemez ya da alamaz.",
        "etik2.6":"Çalışanlarımız kara para ve yolsuzlukla mücadele konusunda yürürlükteki bütün yasa ve yönetmeliklere uygun hareket etmekle sorumludur.",
        "etik2.7":"Çalışanlarımıza ait bilgiler sadece gereksinim durumunda yetkili kişilerce Magma Grup’un amaçları doğrultusunda kullanılır.",
        "etik2.8":"Grup çalışanlarımızın çalışmaları kapsamında elde ettiği gizli bilgileri koruması ve sadece şirket amaçları için kullanması beklenir. Gizli bilgi, şirkete ait olan ve üçüncü kişiler tarafından bilinmeyen, bilinmesi halinde şirket ve/veya paydaşları için zarara sebep olabilecek veya diğerleri için fayda sağlayabilecek, finansal, stratejik, teknik, ticari, personel özlük hakları, üçüncü taraflar ile yapılan gizlilik sözleşmesi kapsamındaki konular ve benzeri bilgiler olarak tanımlanabilir.",

        "etik3.1":"İş sağlığı ve güvenliğinin tam anlamıyla sağlanması hedeflenmiştir. Çalışanlar bu amaçla konulan kural ve talimatlara uygun hareket ederler ve gerekli önlemleri alırlar.",
        "etik3.2":"Çalışanlar, işyeri ve/veya işçiler bakımından tehlike arz eden veya yasa dışı nitelikteki hiçbir eşya ya da maddeyi işyerinde bulunduramazlar..",

        "etik4.1":"Magma Grup atıkların ve ürünlerin çevre üzerindeki olumsuz etkilerini en az düzeye indirecek, doğal kaynak kullanımını azaltacak, mümkün olan en uygun yöntemleri kullanır.",
        "etik4.2":"Magma Grup çevreyi korumak ve temiz tutmak amacıyla, sınırlı kaynakları korumayı, enerji tasarrufunu esas alır.",

        "etik5.1":"Magma Grup, iş ortakları, müşterileri, tedarikçileri ve diğer paydaşları ile ilişkilerinde daima güven ve dürüstlüğü esas alarak, profesyonel ve adil bir şekilde davranır. Karşılıklı yükümlülüklerin zamanında yerine getirilmesi için gereken özeni gösterir.",
        "etik5.2":"Tedarikçi, bayi, yetkili satıcı ve yetkili servis seçimlerimizde insan haklarına önem veren, rüşvet ve yolsuzlukla mücadele ilkelerini dikkate alan, yasal yükümlülüklerini yerine getirilmesini objektif olarak değerlendiririz.",



        


    }
};

document.addEventListener("DOMContentLoaded", function () {
    const languageToggle = document.getElementById('language-toggle');
    const languageText = document.getElementById('language-text');

    languageToggle.addEventListener('change', () => {
        const language = languageToggle.checked ? 'en' : 'tr';
        localStorage.setItem('preferredLanguage', language);
        languageText.textContent = language === 'en' ? 'English' : 'Türkçe';
        loadLanguage(language);
    });

    function loadLanguage(language) {
        const translation = translations[language];
        if (translation) {
            document.querySelectorAll('[data-key]').forEach(element => {
                const key = element.getAttribute('data-key');
                if (translation[key]) {
                    element.textContent = translation[key];
                }
            });
        }
    }

    const preferredLanguage = localStorage.getItem('preferredLanguage') || 'tr';
    languageToggle.checked = (preferredLanguage === 'en');
    languageText.textContent = preferredLanguage === 'en' ? 'English' : 'Türkçe';
    loadLanguage(preferredLanguage);
});
